version: "3.8"
services:
  homeDB:
    image: mariadb:11.3
    restart: always
    env_file: .env
    ports:
      - "3315:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - ./mariadb_data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8085:80"
    environment:
      - PMA_HOST=homeDB
    depends_on:
      - homeDB
    networks:
      - backend

volumes:
  mariadb_data:

networks:
  backend:
