version: "3.8"
services:
  mariadb:
    image: mariadb:11.3
    restart: always
    ports:
      - 3310:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    depends_on:
      - mariadb

volumes:
  mariadb_data:
